name: message slack

on:
  schedule:
    - cron: '5 17 * * *'
  workflow_dispatch:

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  
jobs:
  message_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          python -m pip install -r requirements.txt

      - name: message slack
        run: |
          python message_slack_tito.py
