name: message slack

on:
  schedule:
    - cron:  '1 * * * *'
    
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          python -m pip install -e .

      - name: message slack
        run: |
          python -m 
